# -*- coding: utf-8 -*-
"""Sentence Similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sowp9Xreo3FfcHRLls6_P2F-dBXub0ac
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer,util

#load the model
model = SentenceTransformer('all-MiniLM-L6-V2')

#Take input from user
text1 = input("enter Text 1: ")
text2 = input("enter Text 2: ")

#convert text to embeddings
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)

#calculate similarity
similarity = util.cos_sim(embedding1, embedding2)

#show result
print("\nSimilarity Score:", round(float(similarity),2))

if similarity > 0.75:
  print("Similarity Level: High")
elif similarity > 0.4:
  print("Similarity Level: Medium")
else :
  print("Similarity Level: Low")

"""# New Section"""